# Generated by Django 3.1.3 on 2021-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('filepath', models.FileField(blank=True, null=True, upload_to='files', verbose_name='filepath')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ads', verbose_name='photo')),
                ('video', models.FileField(blank=True, default='', null=True, upload_to='videos', verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pic_folder')),
            ],
        ),
    ]
