# Generated by Django 3.1.3 on 2021-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='filepath',
        ),
        migrations.AlterField(
            model_name='ads',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ads'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
